plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
  - testing-library
  - babel

env:
  node: true
  jest: true
  browser: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  
parser: babel-eslint
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: 0 
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]